// Ink journal unit tests — run with: node test.js
const fs=require('fs'),assert=require('assert');
const code=fs.readFileSync('app.js','utf8');
const ctl=()=>({value:"",addEventListener(t,f){this["h"+t]=f},dispatch(t,ev={}){const h=this["h"+t];if(h)h({preventDefault(){},...ev})},focus(){}});
const star=()=>{const o={attrs:{},cls:{},setAttribute(k,v){o.attrs[k]=String(v)},classList:{toggle(c,f){o.cls[c]=f}}};return o};
const el=()=>({value:"",textContent:"",innerHTML:"",id:"",dataset:{},children:[],style:{},open:false,closed:false,classList:{toggle(){}},setAttribute(){},addEventListener(t,f){this["h"+t]=f},dispatch(t,ev={}){const h=this["h"+t];if(h)h({preventDefault(){},target:ev.target||this,...ev})},close(){this.closed=true;this.dispatch("close")},showModal(){this.open=true},reset(){},focus(){}});
const els={};
global.document={querySelector(s){if(!els[s]){els[s]=el();if(s==="#form"){for(const n of["name","brand","color","notes","rating"])els[s][n]=ctl();}if(s==="#stars"){els[s].children=Array.from({length:5},()=>star());}}return els[s];}};
let saved=null,alertMsg="";
global.localStorage={getItem:()=>null,setItem:(k,v)=>{saved=v}};
global.confirm=()=>true;
global.alert=m=>{alertMsg=m};
const $=s=>document.querySelector(s);
const form=$("#form"),dlg=$("#dlg"),grid=$("#grid"),status=$("#status"),count=$("#count");
const search=$("#search"),starsEl=$("#stars"),hex=$("#hex"),dlgTitle=$("#dlgTitle");
const customEl=$("#custom"),shadeEl=$("#shade"),presetsEl=$("#presets"),previewEl=$("#preview");
global.localStorage.getItem=()=>JSON.stringify([
{id:"a1",name:"Oxblood",brand:"Diamine",color:"#6d1828",notes:"Rich burgundy.",rating:3.5,createdAt:100},
{id:"a2",name:"Kon-Peki",brand:"Iroshizuku",color:"#2ea8e0",notes:"",rating:5,createdAt:200},
{id:5,name:"Bad id",brand:"B",color:"#000000",notes:"",rating:1,createdAt:50},
{name:"No id",brand:"B",color:"#000000",notes:"",rating:1,createdAt:50},
{id:"a3",name:"Bad color",brand:"B",color:"red",notes:"",rating:1,createdAt:50}]);
eval(code+String.raw`
assert.strictEqual(inks.length,2);
assert(grid.innerHTML.includes("Oxblood"));
assert(grid.innerHTML.includes("Kon-Peki"));
assert(grid.innerHTML.indexOf("Kon-Peki")<grid.innerHTML.indexOf("Oxblood"));
assert(grid.innerHTML.includes("aria-label=\"4 out of 5\""));
assert.strictEqual(count.textContent,"2 inks");
assert.strictEqual(status.innerHTML,"");
assert.strictEqual(esc("<b>&\"'x"),"&lt;b&gt;&amp;&quot;&#39;x");
assert.strictEqual(esc("a\"b"),"a&quot;b");
assert.strictEqual(starStr(3),"★★★☆☆");
assert.notStrictEqual(uid(),uid());
localStorage.getItem=()=>"garbage";
assert.deepStrictEqual(load(),[]);
localStorage.getItem=()=>"{\"a\":1}";
assert.deepStrictEqual(load(),[]);
localStorage.getItem=()=>JSON.stringify([null,{id:"1",name:"N",brand:"B",color:"#000000"}]);
assert.strictEqual(load().length,1);
localStorage.getItem=()=>JSON.stringify([{id:"1",name:5,brand:"B",color:"#000000"},{id:"2",name:"X",brand:"Y",color:"#000000",notes:"",rating:3,createdAt:1}]);
assert.strictEqual(load().length,1);
localStorage.getItem=()=>null;
form.name.value="  Oxblood  ";
form.brand.value="Diamine";
form.color.value="#6d1828";
form.notes.value="Rich burgundy";
form.rating.value="5";
form.dispatch("submit");
assert.strictEqual(inks.length,3);
assert.strictEqual(inks[2].name,"Oxblood");
assert.strictEqual(inks[2].rating,5);
assert.strictEqual(dlg.closed,true);
assert.strictEqual(JSON.parse(saved).length,3);
assert.strictEqual(JSON.parse(saved)[2].name,"Oxblood");
form.name.value="   ";
form.brand.value="Diamine";
form.color.value="#000000";
form.notes.value="";
form.rating.value="3";
form.dispatch("submit");
assert.strictEqual(inks.length,3);
inks.push({id:"u\"3\"",name:"<script>alert(1)</script>",brand:"Evil",color:"#ff0000",notes:"",rating:2,createdAt:3});
render();
assert(!grid.innerHTML.includes("<script>alert(1)</script>"));
assert(grid.innerHTML.includes("&lt;script&gt;"));
assert(!grid.innerHTML.includes("data-id=\"u\""));
assert(grid.innerHTML.includes("data-id=\"u&quot;3&quot;\""));
const id=inks[0].id;
openForm(id);
assert.strictEqual(form.name.value,"Oxblood");
assert.strictEqual(dlgTitle.textContent,"Edit ink");
form.name.value="Oxblood 2";
form.notes.value="";
form.rating.value="4";
form.dispatch("submit");
assert.strictEqual(inks.length,4);
assert.strictEqual(inks[0].id,id);
assert.strictEqual(inks[0].name,"Oxblood 2");
assert.strictEqual(inks[0].rating,4);
inks.push({id:"m9",name:"Nine",brand:"B",color:"#ffffff",notes:"",rating:9,createdAt:4});
inks.push({id:"m35",name:"Float",brand:"B",color:"#ffffff",notes:"",rating:3.5,createdAt:5});
openForm("m9");
assert.strictEqual(form.rating.value,5);
openForm("m35");
assert.strictEqual(form.rating.value,4);
dlg.dispatch("close");
assert.strictEqual(editingId,null);
global.confirm=()=>false;
grid.dispatch("click",{target:{closest:s=>s==="button[data-act]"?{dataset:{act:"del",id:"m9"}}:null}});
assert.strictEqual(inks.length,6);
global.confirm=()=>true;
grid.dispatch("click",{target:{closest:s=>s==="button[data-act]"?{dataset:{act:"del",id:"m9"}}:null}});
assert.strictEqual(inks.length,5);
assert.strictEqual(inks.find(i=>i.id==="m9"),undefined);
search.value="kon";
search.dispatch("input");
assert(grid.innerHTML.includes("Kon-Peki"));
assert(!grid.innerHTML.includes("Oxblood 2"));
search.value="EVIL";
search.dispatch("input");
assert(grid.innerHTML.includes("&lt;script&gt;"));
search.value="";
search.dispatch("input");
assert(grid.innerHTML.includes("Oxblood 2"));
search.value="zzz";
search.dispatch("input");
assert(status.innerHTML.includes("No inks match"));
search.value="";
starsEl.dispatch("click",{target:{closest:s=>s==="button"?{value:"2"}:null}});
assert.strictEqual(form.rating.value,2);
assert.strictEqual(starsEl.children[0].attrs["aria-pressed"],"true");
assert.strictEqual(starsEl.children[1].attrs["aria-pressed"],"true");
assert.strictEqual(starsEl.children[2].attrs["aria-pressed"],"false");
assert.strictEqual(starsEl.children[0].cls["on"],true);
assert.strictEqual(starsEl.children[2].cls["on"],false);
starsEl.dispatch("click",{target:{closest:s=>s==="button"?{value:"5"}:null}});
assert.strictEqual(form.rating.value,5);
assert.strictEqual(starsEl.children[4].attrs["aria-pressed"],"true");
presetsEl.dispatch("click",{target:{closest:s=>s==="button[data-c]"?{dataset:{c:"#2ea8e0"}}:null}});
assert.strictEqual(customEl.value,"#2ea8e0");
assert.strictEqual(form.color.value,"#2ea8e0");
assert.strictEqual(hex.textContent,"#2ea8e0");
shadeEl.value=25;shadeEl.dispatch("input");
assert.strictEqual(form.color.value,"#175470");
assert.strictEqual(previewEl.style.background,"#175470");
shadeEl.value=0;shadeEl.dispatch("input");
assert.strictEqual(form.color.value,"#000000");
shadeEl.value=100;shadeEl.dispatch("input");
assert.strictEqual(form.color.value,"#ffffff");
shadeEl.value=50;
customEl.value="#123456";customEl.dispatch("input");
assert.strictEqual(form.color.value,"#123456");
assert.strictEqual(hex.textContent,"#123456");
assert.strictEqual(previewEl.style.background,"#123456");
openForm(inks.find(i=>i.name==="Oxblood 2").id);
assert.strictEqual(customEl.value,"#6d1828");
assert.strictEqual(form.color.value,"#6d1828");
assert.strictEqual(shadeEl.value,50);
openForm(inks.find(i=>i.name==="Kon-Peki").id);
form.color.value="zzz";
form.notes.value="";
form.dispatch("submit");
assert.strictEqual(inks.find(i=>i.name==="Kon-Peki").color,"#6d1828");
inks.push({id:"nc",name:"NoDate",brand:"B",color:"#000000",notes:"",rating:1});
render();
assert(grid.innerHTML.includes("NoDate"));
inks=[];
render();
assert(status.innerHTML.includes("Your ink shelf is empty"));
assert.strictEqual(count.textContent,"");
status.dispatch("click",{target:{id:"emptyAdd"}});
assert.strictEqual(dlg.open,true);
assert.strictEqual(dlgTitle.textContent,"Add ink");
assert.strictEqual(customEl.value,"#6d1828");
assert.strictEqual(form.color.value,"#6d1828");
localStorage.setItem=()=>{throw new Error("full")};
form.name.value="X";
form.brand.value="Y";
form.color.value="#000000";
form.notes.value="";
form.rating.value="3";
form.dispatch("submit");
assert(alertMsg.includes("storage"));
console.log("all checks passed");
`);
